spring.application.name=jobposting
server.port=8081
# MongoDB connection (adjust if your Mongo is different)
spring.data.mongodb.uri=mongodb://localhost:27017/jobposting

# Optional: show less noisy logs
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO

